### ISSUE TITLE
Using pre-trained MLP in DiffTre

### ISSUE THREAD

**Issue by longkunxuluke** [tummfm/difftre#5]
Greetings. We are interested in using pre-trained MLP in DiffTre but we found there is no available example in the three notebooks you shared. In the paper we noticed you mentioned it would be a future work, I am wondering if you have more updated papers/demos showing how to use pre-trained MLP in DiffTre, or if you have any suggestions in this regard, e.g., which types of pre-trained MLP is supported with current DiffTre framework? Many thanks !

**Comment by S-Roecken** [comment]
Hi, we currently have a paper in review that employs a pre-trained MLP. For details see: https://www.researchgate.net/publication/374051787_Accurate_machine_learning_force_fields_via_experimental_and_simulation_data_fusion

Best
Sebastien
