### ISSUE TITLE
Installation with pip

### ISSUE THREAD

**Issue by jgreener64** [tummfm/difftre#6]
Great package!

Just letting you know that I had to use the following command to get a compatible environment:
```bash
pip install chex==0.0.9 MDAnalysis jax==0.2.17 jaxlib==0.1.68 jax-md==0.1.13 optax==0.0.9 dm-haiku==0.0.4 sympy==1.8 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```
This is because a) recent chex versions used a different jax version and b) jaxlib==0.1.68 is no longer available via simple `pip install`.

**Comment by S-Thaler** [comment]
Thanks for the heads-up! 
This package now mostly contains the reference implementation of the paper. If you're interested in an extended and more up-to-date version, feel free to check out [chemtrain](https://github.com/tummfm/chemtrain). We hope to publish a new version of chemtrain in a few months and also keep the package better maintained.

**Comment by jgreener64** [comment]
chemtrain looks cool, interested to see where it goes.
